export const testingLibraries: { [key: string]: string[] } = {
  c: [
    "Unity",
    "CppUTest",
    "GoogleTest",
    "CUnit",
    "Boost.Test",
    "Catch",
    "CppUnit",
    "Embunit",
    "Mockito",
  ],
  csharp: [
    "NUnit",
    "XUnit",
    "MSTest",
    "SpecFlow",
    "Selenium",
    "Appium",
    "White",
    "Mockito",
  ],
  cpp: [
    "GoogleTest",
    "CppUTest",
    "Catch",
    "Boost.Test",
    "CppUnit",
    "Embunit",
    "Mockito",
  ],
  dart: ["Flutter", "FlutterDriver", "Mockito", "Test", "TestWidgets"],
  go: ["testing", "GoConvey", "Ginkgo", "Gomega", "Testify", "TestRunner"],
  java: [
    "JUnit",
    "TestNG",
    "Cucumber",
    "Selenium",
    "Appium",
    "RestAssured",
    "Mockito",
    "PowerMock",
  ],
  javascript: [
    "Cypress",
    "Jasmine",
    "Jest",
    "Karma",
    "MochaJS",
    "NightwatchJS",
    "Playwright",
    "Puppeteer",
    "Selenium",
  ],
  perl: [
    "Test::Simple",
    "Test::More",
    "Test::Class",
    "Test::Unit",
    "Test::MockObject",
    "Test::MockModule",
  ],
  php: ["PHPUnit", "Codeception", "Behat", "PHPSpec", "Mockery", "Prophecy"],
  python: [
    "unittest",
    "pytest",
    "nose",
    "doctest",
    "tox",
    "behave",
    "lettuce",
    "robot",
  ],
  r: ["testthat", "RUnit", "RUnitLite", "svUnit", "testit", "tinytest"],
  ruby: [
    "RSpec",
    "Cucumber",
    "Minitest",
    "Test::Unit",
    "Capybara",
    "Selenium",
    "Watir",
    "Appium",
  ],
  rust: ["Rust", "Cargo", "RustUnit", "RustTest", "RustMock", "RustAssert"],
  swift: ["XCTest", "Quick", "Kiwi", "Specta", "Cucumberish", "Mockingjay"],
  typescript: [
    "Jasmine",
    "Jest",
    "Cucumber",
    "Protractor",
    "Selenium",
    "Appium",
    "Mockito",
  ],
};
